jobs:
- job: Default
  timeoutInMinutes: 90
  pool:
    vmImage: Ubuntu-16.04
  steps:
  - script: |
      nproc
      lscpu
    displayName: 'Machine info'
  - script: |
      sudo chown -R $USER $CONDA
      . $CONDA/etc/profile.d/conda.sh
      conda create --yes --quiet --name paparazzi python=3.7.3 pip
    displayName: 'Setup conda'
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate paparazzi
      conda install -y -q numpy scipy mkl openblas theano
      theano-cache purge
      pip install -U pip
      pip install -U setuptools
      pip install -U -r requirements.txt
      conda install -y -q -c conda-forge tectonic
      python setup.py develop
    displayName: 'Install dependencies'
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate paparazzi
      cd $(Build.SourcesDirectory)/tex
      make
    displayName: 'Build the paper'
    #condition: contains(variables['Build.SourceVersionMessage'], '[build paper]')
  - script: |
      cd $(Build.SourcesDirectory)
      git checkout --orphan $(Build.SourceBranchName)-pdf
      git rm -rf --cached .
      git add -f tex/ms.pdf
      git add -f tex/figures/*.pdf
      git -c user.name='azure' -c user.email='azure' commit -m "building the paper"
      git push -q -f https://$(GITHUB_USER):$(GITHUB_API_KEY)@github.com/rodluger/paparazzi $(Build.SourceBranchName)-pdf >/dev/null 2>&1
    displayName: 'Upload the paper'
    #condition: contains(variables['Build.SourceVersionMessage'], '[build paper]')