# no pull requests
pr: none

pool:
  vmImage: Ubuntu-16.04

steps:

- script: |
    sudo chown -R $USER $CONDA
    . $CONDA/etc/profile.d/conda.sh
    conda create --yes --quiet --name paparazzi python=3.7 pip
  displayName: 'Setup conda'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate paparazzi
    pip install -U pip
    pip install -U setuptools
    pip install -U -r requirements.txt
    conda install -y -q -c conda-forge tectonic
    theano-cache purge

    python setup.py install
  displayName: 'Install dependencies'

- script: |
    . $CONDA/etc/profile.d/conda.sh
    conda activate paparazzi
    cd $(Build.SourcesDirectory)/tex
    make
  displayName: 'Build the paper'

- script: |
    cd $(Build.SourcesDirectory)
    git checkout --orphan $(Build.SourceBranchName)-pdf
    git rm -rf --cached .
    git add -f tex/ms.pdf
    git add -f tex/figures/*.pdf
    git -c user.name='azure' -c user.email='azure' commit -m "building the paper"
    git push -q -f https://$(GITHUB_USER):$(GITHUB_API_KEY)@github.com/rodluger/paparazzi $(Build.SourceBranchName)-pdf >/dev/null 2>&1
  displayName: 'Upload the paper'
  condition: always()