name: paparazzi
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl-service>=2.3.0
  - pip>=20.3.3
  - python=3.7.3
  - scipy>=1.5.2
  - pip:
      - matplotlib>=3.3.3
      - tqdm>=4.56.0
      - git+https://github.com/rodluger/starry.git@7c55fcebef629b11f49cc28ad29485ac70e0267d#egg=starry
