
name: article

on: push

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Build the article PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build the article PDF
        id: build
        uses: rodluger/showyourwork/showyourwork-action@c6c8e598bea4f48f8e8ae1f73c84d4d9386e6254

